# Generated by Django 3.0.3 on 2020-11-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeId', models.IntegerField()),
                ('routeShortName', models.CharField(max_length=10)),
                ('routeLongName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopId', models.IntegerField()),
                ('stopName', models.CharField(max_length=100)),
                ('stopLat', models.FloatField()),
                ('stopLon', models.FloatField()),
                ('onDemand', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopSequence', models.IntegerField()),
                ('arrivalTime', models.DateField()),
                ('date', models.DateField()),
                ('busServiceName', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Stop')),
            ],
        ),
    ]
