# Generated by Django 3.0.3 on 2020-11-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stopName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
