# Generated by Django 3.0.3 on 2020-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20201128_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='onDemand',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
