# Generated by Django 3.0.3 on 2020-11-28 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_auto_20201128_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='stopName',
        ),
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 13, 12, 7, 595013)),
        ),
        migrations.AddField(
            model_name='stop',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 13, 12, 7, 595013)),
        ),
        migrations.AddField(
            model_name='stop',
            name='stopDesc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
