# Generated by Django 3.0.3 on 2020-11-28 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_auto_20201128_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 12, 15, 56, 655031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stop',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 12, 15, 56, 655031, tzinfo=utc)),
        ),
    ]
