# Generated by Django 3.0.3 on 2020-11-28 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_auto_20201128_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stop',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
