# Generated by Django 3.0.3 on 2020-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_auto_20201128_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='arrivalTime',
            field=models.DateTimeField(),
        ),
    ]
